sudo: required
services:
- docker


before_install:
- docker build -t dineshsonachalam/deploy_flask_app_with_gunicorn:1.0.1 .
script:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to Docker hub
  - docker push dineshsonachalam/deploy_flask_app_with_gunicorn:1.0.1
